- hosts: localhost
  gather_facts: no
  vars_files:
        - cred.yml
  tasks:
    - name: Running EC2 Role
      include_role:
        name: ec2

- hosts: ec2_master
  gather_facts: no
  vars_files:
    - cred.yml
  tasks:
    - name: Running K8s Master Role
      include_role:
        name: k8s_master

- hosts: ec2_slave
  gather_facts: no
  tasks:
    - name: Running K8s Slave Role
      include_role:
        name: k8s_slave

- hosts: ec2_master
  gather_facts: no
  vars_files:
    - cred.yml
  environment:
    AWS_REGION: ap-northeast-2
    AWS_ACCESS_KEY_ID: "ASIA5TRKJVUQUPYSORYI"
    AWS_SECRET_ACCESS_KEY: "nrdDdezV3a4rLKvb1DXjNh+pFSUfp6i8AIagRs0m"
    AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEPj//////////wEaDmFwLW5vcnRoZWFzdC0yIkcwRQIgZaozYVsIQhgtfaJwloCG9ogO8v9Ifx4TvX5kVe8WtI8CIQCs5YzLvpkAkL89Jo6hIcrtS2MmtvMXnTAXi8ZKmt8cUCr4AQiR//////////8BEAIaDDkzNTMxNzg0MzIzMyIMx2wfoDn0Hqo9ZLQwKswBWRz9YLF2sJWNBZgxUxh87/AeEEHv7T7KlOBmGA3kukUpMuBf0WKEGVh9d5QgDZ1NnkdJmCIbYhN+Op3d8V7yqCQM3i+CwzwLtcoRdNxQzDoLRUSU9u5IKt1w0LcuZJ2Vc3OYrhCZz6rokvAWZ1kp7bjh0ESd3hTKWWE5sKsG2vK9ih3gnyUjtluDIYLKHBhLO1qcJLNmDFfEkxS8XI1f/+wx1yEVjEZ9ugZCXyG+RlPWEOShqR1LSYWUtJvXqMlmMPjxOe5Oov6XJi91MNK3rLMGOpgBwOj+c7vCql0hhfVNr5QZwIbj4ZmdFkXXF2yBIQ6z7EbA8qC569waKKwqxiE7mS136PVXOCmiBWQw8oM5Y+dYWQNYqAPMnun8DdFgGS3kEJcYe9orUlUrpT5RilTIb9JJ+/T7TfvQWFq4IsGyytSns4wFrFW9JnX+4rvRIAV7dXgKOxq0ht6SoDEfSQOr3l7eBmdZaGtuiDc="
  tasks:
    - name: Running CAPA Role
      include_role:
        name: capa

- hosts: ec2_master
  gather_facts: no
  vars_files:
     - mgmt.yml
  tasks:
    - name: Running K8s Master Nephio Bootstrap
      ansible.builtin.include_tasks: cluster.yml