---
# vars file for ec2

instance_tag:
        - master
        - slave1
        - slave2

python_pkgs:
        - boto
        - boto3

sg_name: default
region_name: ap-northeast-2 
subnet_name: subnet-06e9023cfce9b9ce6
# ami_id: ami-09a7535106fbd42d5 #ubuntu 22.04 LTS
ami_id: ami-08b2c3a9f2695e351 #ubuntu 20.04 LTS
vpc_id: vpc-009b499b58b133ae8
keypair: nephio3
instance_flavour: c5.4xlarge